/* 钛虎机器人 · 供应链看板 — 演示假数（贴近飞书/金蝶语义） */
window.TAIHU_DATA = {
  meta: {
    brand: "钛虎机器人",
    title: "供应链看板",
    footer: "演示数据",
  },

  books: [
    { id: "all", label: "全部账套" },
    { id: "TH-A", label: "钛虎机器人（主体）" },
    { id: "TH-B", label: "钛虎精密部件" },
    { id: "TH-C", label: "钛虎智造科技" },
  ],

  pulse: [
    {
      id: "in-transit",
      label: "采购在途",
      value: 128,
      unit: "单",
      delta: "+12",
      tone: "neutral",
      sub: "金额 ¥18.6M",
      mom: { label: "环比", value: "+10.3%", dir: "up" },
      yoy: { label: "同比", value: "+18.6%", dir: "up" },
      drill: [
        { no: "PO2026080012", supplier: "宁波精工传动", amount: "¥286,400", eta: "08-08", status: "在途" },
        { no: "PO2026080028", supplier: "上海钛合金材", amount: "¥152,000", eta: "08-09", status: "部分到货" },
        { no: "PO2026080041", supplier: "苏州伺服系统", amount: "¥98,600", eta: "08-07", status: "在途·加急" },
        { no: "PO2026080055", supplier: "杭州线束科技", amount: "¥41,200", eta: "08-10", status: "在途" },
        { no: "PO2026080063", supplier: "东莞结构件", amount: "¥67,800", eta: "08-11", status: "在途" },
        { no: "PO2026080071", supplier: "无锡轴承", amount: "¥23,500", eta: "08-12", status: "在途" },
      ],
    },
    {
      id: "approval-overdue",
      label: "审批超时",
      value: 7,
      unit: "单",
      delta: "+3",
      tone: "warn",
      sub: "最长 26.5h",
      mom: { label: "环比", value: "+75.0%", dir: "warn" },
      yoy: { label: "同比", value: "-12.5%", dir: "down" },
      drill: [
        { no: "FS-URG-0821", type: "紧急临时采购", node: "采购经理", stay: "18.2h", sla: "8h" },
        { no: "FS-RD-0794", type: "研发部门采购", node: "财务审核", stay: "26.5h", sla: "16h" },
        { no: "FS-REQ-1102", type: "采购需求申请", node: "部门负责人", stay: "14.0h", sla: "12h" },
        { no: "FS-URG-0833", type: "紧急临时采购", node: "财务", stay: "9.1h", sla: "8h" },
        { no: "FS-RD-0801", type: "研发部门采购", node: "研发总监", stay: "17.4h", sla: "16h" },
      ],
    },
    {
      id: "iqc-rate",
      label: "来料合格率",
      value: 96.4,
      unit: "%",
      delta: "-0.8pp",
      tone: "good",
      sub: "不合格 44 批",
      mom: { label: "环比", value: "-0.8pp", dir: "down" },
      yoy: { label: "同比", value: "+1.2pp", dir: "up" },
      drill: [
        { date: "08-05", pass: 42, fail: 2, rate: "95.5%" },
        { date: "08-04", pass: 38, fail: 1, rate: "97.4%" },
        { date: "08-03", pass: 51, fail: 3, rate: "94.4%" },
        { date: "08-02", pass: 29, fail: 0, rate: "100%" },
        { date: "08-01", pass: 44, fail: 2, rate: "95.7%" },
      ],
    },
    {
      id: "otd",
      label: "交货及时率",
      value: 91.2,
      unit: "%",
      delta: "+1.4pp",
      tone: "good",
      sub: "延期 11 单",
      mom: { label: "环比", value: "+1.4pp", dir: "up" },
      yoy: { label: "同比", value: "+3.8pp", dir: "up" },
      drill: [
        { no: "PO202607088", supplier: "苏州伺服系统", due: "07-28", actual: "07-30", late: "2天" },
        { no: "PO202607102", supplier: "宁波精工传动", due: "08-01", actual: "08-01", late: "准时" },
        { no: "PO202607115", supplier: "东莞结构件", due: "08-03", actual: "08-05", late: "2天" },
        { no: "PO202607128", supplier: "杭州线束科技", due: "08-04", actual: "08-04", late: "准时" },
        { no: "PO202607140", supplier: "上海钛合金材", due: "08-05", actual: "08-07", late: "2天" },
      ],
    },
    {
      id: "inv-risk",
      label: "库存风险",
      value: 14,
      unit: "SKU",
      delta: "+2",
      tone: "warn",
      sub: ">180天 6%",
      mom: { label: "环比", value: "+16.7%", dir: "warn" },
      yoy: { label: "同比", value: "-22.2%", dir: "down" },
      drill: [
        { sku: "RM-SERVO-M2", name: "伺服电机 M2", age: "186天", qty: 28, flag: "高库龄" },
        { sku: "RM-AL-6061", name: "铝合金板 6061", age: "142天", qty: 120, flag: "呆滞候选" },
        { sku: "RM-HARN-12", name: "线束组件 12P", age: "98天", qty: 64, flag: "关注" },
        { sku: "RM-BEAR-6204", name: "轴承 6204", age: "210天", qty: 400, flag: "高库龄" },
      ],
    },
  ],

  approvalFlows: [
    {
      id: "urgent",
      name: "紧急临时采购",
      avgHours: 9.6,
      sla: 8,
      overdue: 3,
      volume: 42,
      heat: [2, 4, 6, 8, 5, 3, 7, 9, 4, 2],
      nodes: [
        { name: "发起人", avg: 0.2 },
        { name: "直属主管", avg: 2.1 },
        { name: "采购经理", avg: 4.8 },
        { name: "财务", avg: 2.5 },
      ],
    },
    {
      id: "rd",
      name: "研发部门采购",
      avgHours: 14.2,
      sla: 16,
      overdue: 2,
      volume: 68,
      heat: [1, 3, 5, 7, 6, 4, 8, 5, 3, 2],
      nodes: [
        { name: "研发发起", avg: 0.3 },
        { name: "项目经理", avg: 3.4 },
        { name: "研发总监", avg: 5.6 },
        { name: "采购", avg: 2.8 },
        { name: "财务", avg: 2.1 },
      ],
    },
    {
      id: "req",
      name: "采购需求申请",
      avgHours: 11.8,
      sla: 12,
      overdue: 2,
      volume: 156,
      heat: [3, 5, 8, 10, 7, 6, 9, 11, 6, 4],
      nodes: [
        { name: "需求人", avg: 0.4 },
        { name: "部门负责人", avg: 4.2 },
        { name: "采购执行", avg: 3.6 },
        { name: "财务审核", avg: 3.6 },
      ],
    },
    {
      id: "precision",
      name: "精密加工采购需求",
      avgHours: null,
      sla: null,
      overdue: 0,
      volume: 0,
      optional: true,
      note: "可选",
      heat: [],
      nodes: [],
    },
  ],

  heatLabels: ["D-9", "D-8", "D-7", "D-6", "D-5", "D-4", "D-3", "D-2", "D-1", "今日"],

  approvalRank: [
    { name: "王敏 · 采购经理", overdue: 4, avgStay: "6.2h", flow: "紧急/需求" },
    { name: "李哲 · 财务审核", overdue: 3, avgStay: "5.1h", flow: "研发/需求" },
    { name: "陈远 · 部门负责人", overdue: 2, avgStay: "4.4h", flow: "需求申请" },
    { name: "赵晴 · 研发总监", overdue: 1, avgStay: "3.8h", flow: "研发采购" },
    { name: "周凯 · 项目经理", overdue: 1, avgStay: "3.2h", flow: "研发采购" },
  ],

  approvalOverdueList: [
    { no: "FS-RD-0794", type: "研发部门采购", node: "财务审核", stay: 26.5, sla: 16, owner: "李哲", book: "TH-A" },
    { no: "FS-URG-0821", type: "紧急临时采购", node: "采购经理", stay: 18.2, sla: 8, owner: "王敏", book: "TH-A" },
    { no: "FS-RD-0801", type: "研发部门采购", node: "研发总监", stay: 17.4, sla: 16, owner: "赵晴", book: "TH-A" },
    { no: "FS-REQ-1102", type: "采购需求申请", node: "部门负责人", stay: 14.0, sla: 12, owner: "陈远", book: "TH-B" },
    { no: "FS-URG-0833", type: "紧急临时采购", node: "财务", stay: 9.1, sla: 8, owner: "李哲", book: "TH-A" },
    { no: "FS-REQ-1118", type: "采购需求申请", node: "采购执行", stay: 13.2, sla: 12, owner: "王敏", book: "TH-C" },
  ],

  sampleTimeline: {
    title: "FS-REQ-1108 → CGSQ2508060021 → PO2026080041",
    steps: [
      { sys: "飞书", name: "采购需求申请提交", time: "08-04 09:12", stay: "—", status: "done", detail: "物料清单_关节模组.xlsx" },
      { sys: "金蝶", name: "生成采购申请单", time: "08-04 09:18", stay: "6m", status: "done", detail: "CGSQ2508060021 回填飞书" },
      { sys: "金蝶", name: "下推采购订单", time: "08-04 11:40", stay: "2.4h", status: "done", detail: "PO2026080041 · 苏州伺服" },
      { sys: "飞书", name: "PO 审核同步", time: "08-04 14:05", stay: "2.4h", status: "warn", detail: "采购经理节点 · 超 SLA" },
      { sys: "金蝶", name: "回写「已审核」", time: "08-04 14:12", stay: "7m", status: "done", detail: "单据状态：已审核" },
      { sys: "金蝶", name: "收料通知", time: "08-06 10:20", stay: "—", status: "done", detail: "SLTZ2508060018" },
      { sys: "金蝶", name: "采购入库 · 来料检验", time: "08-06 15:45", stay: "—", status: "active", detail: "检验中 · 待确认" },
      { sys: "金蝶", name: "应付", time: "—", stay: "—", status: "pending", detail: "待入库完成后生成" },
    ],
  },

  chainFunnel: [
    { stage: "飞书申请", count: 186 },
    { stage: "采购申请回填", count: 178 },
    { stage: "下推 PO", count: 162 },
    { stage: "飞书审核通过", count: 151 },
    { stage: "收料通知", count: 128 },
    { stage: "采购入库", count: 119 },
    { stage: "应付", count: 102 },
  ],

  openPos: [
    { no: "PO2026080041", supplier: "苏州伺服系统", amount: "¥98,600", type: "非标", rd: "研发", status: "已审核·在途", eta: "08-07", otdRisk: "加急" },
    { no: "PO2026080012", supplier: "宁波精工传动", amount: "¥286,400", type: "标准", rd: "非研发", status: "在途", eta: "08-08", otdRisk: "正常" },
    { no: "PO2026080028", supplier: "上海钛合金材", amount: "¥152,000", type: "标准", rd: "非研发", status: "部分到货", eta: "08-09", otdRisk: "正常" },
    { no: "PO2026080055", supplier: "杭州线束科技", amount: "¥41,200", type: "标准", rd: "非研发", status: "在途", eta: "08-10", otdRisk: "正常" },
    { no: "PO2026080063", supplier: "东莞结构件", amount: "¥67,800", type: "非标", rd: "研发", status: "已审核·在途", eta: "08-11", otdRisk: "关注" },
    { no: "PO2026080071", supplier: "无锡轴承", amount: "¥23,500", type: "标准", rd: "非研发", status: "在途", eta: "08-12", otdRisk: "正常" },
  ],

  quality: {
    pass: 1186,
    fail: 44,
    rate: 96.4,
    batches: 1230,
    trend: [97.1, 96.8, 95.9, 96.2, 97.0, 95.5, 96.4],
    labels: ["W-6", "W-5", "W-4", "W-3", "W-2", "W-1", "本周"],
    bySupplier: [
      { supplier: "苏州伺服系统", pass: 86, fail: 8, rate: 91.5, focus: true },
      { supplier: "宁波精工传动", pass: 142, fail: 4, rate: 97.3, focus: false },
      { supplier: "东莞结构件", pass: 98, fail: 9, rate: 91.6, focus: true },
      { supplier: "杭州线束科技", pass: 120, fail: 3, rate: 97.6, focus: false },
      { supplier: "上海钛合金材", pass: 76, fail: 5, rate: 93.8, focus: false },
      { supplier: "无锡轴承", pass: 210, fail: 2, rate: 99.1, focus: false },
    ],
    recentFail: [
      { date: "08-05", sku: "RM-SERVO-M2", supplier: "苏州伺服系统", qty: 4, reason: "尺寸超差" },
      { date: "08-05", sku: "RM-HARN-12", supplier: "杭州线束科技", qty: 2, reason: "端子不良" },
      { date: "08-03", sku: "RM-FRAME-B3", supplier: "东莞结构件", qty: 6, reason: "表面划伤" },
      { date: "08-03", sku: "RM-SERVO-M1", supplier: "苏州伺服系统", qty: 3, reason: "噪音超标" },
      { date: "08-01", sku: "RM-AL-6061", supplier: "上海钛合金材", qty: 8, reason: "厚度偏差" },
    ],
  },

  warehouse: {
    moves: [
      { type: "采购入库", in: 842, out: 0, amount: "¥9.2M" },
      { type: "销售出库", in: 0, out: 618, amount: "¥11.4M" },
      { type: "生产入库", in: 294, out: 0, amount: "¥6.1M" },
      { type: "其他出入库", in: 56, out: 41, amount: "¥0.8M" },
      { type: "退货", in: 18, out: 27, amount: "¥0.4M" },
    ],
    ageBuckets: [
      { label: "0–30天", pct: 48, amount: "¥6.3M" },
      { label: "31–60天", pct: 22, amount: "¥2.9M" },
      { label: "61–90天", pct: 14, amount: "¥1.8M" },
      { label: "91–180天", pct: 10, amount: "¥1.3M" },
      { label: ">180天", pct: 6, amount: "¥0.8M" },
    ],
    stockSummary: { begin: "¥12.4M", in: "¥3.8M", out: "¥3.1M", end: "¥13.1M" },
    riskSkus: [
      { sku: "RM-BEAR-6204", name: "轴承 6204", age: 210, qty: 400, amount: "¥86,000", flag: "高库龄" },
      { sku: "RM-SERVO-M2", name: "伺服电机 M2", age: 186, qty: 28, amount: "¥224,000", flag: "高库龄" },
      { sku: "RM-AL-6061", name: "铝合金板 6061", age: 142, qty: 120, amount: "¥96,000", flag: "呆滞候选" },
      { sku: "RM-HARN-12", name: "线束组件 12P", age: 98, qty: 64, amount: "¥38,400", flag: "关注" },
      { sku: "RM-SEAL-07", name: "密封件套装", age: 165, qty: 220, amount: "¥44,000", flag: "呆滞候选" },
    ],
  },

  projectSummary: [
    { label: "在研项目", value: "12", tone: "neutral" },
    { label: "非标占比", value: "58%", tone: "warn" },
    { label: "研发物料", value: "41%", tone: "neutral" },
    { label: "交期风险", value: "3", tone: "warn" },
  ],

  projects: [
    { code: "P-关节模组-A2", type: "非标", rd: "研发", otd: 88, payPlan: "30/60/10", nextDue: "08-12", risk: "交期紧", amount: "¥1.2M" },
    { code: "P-线束标品-S1", type: "标准", rd: "非研发", otd: 97, payPlan: "月结30", nextDue: "08-09", risk: "正常", amount: "¥0.4M" },
    { code: "P-伺服定制-R7", type: "非标", rd: "研发", otd: 79, payPlan: "预付40%", nextDue: "08-07", risk: "逾期风险", amount: "¥0.9M" },
    { code: "P-结构件-B3", type: "标准", rd: "非研发", otd: 94, payPlan: "月结45", nextDue: "08-15", risk: "正常", amount: "¥0.6M" },
    { code: "P-减速器-N4", type: "非标", rd: "研发", otd: 85, payPlan: "预付30%", nextDue: "08-14", risk: "交期紧", amount: "¥1.5M" },
    { code: "P-控制板-C2", type: "标准", rd: "研发", otd: 92, payPlan: "月结30", nextDue: "08-10", risk: "正常", amount: "¥0.3M" },
    { code: "P-外壳件-H1", type: "标准", rd: "非研发", otd: 96, payPlan: "月结60", nextDue: "08-18", risk: "正常", amount: "¥0.5M" },
    { code: "P-视觉模组-V3", type: "非标", rd: "研发", otd: 81, payPlan: "30/70", nextDue: "08-08", risk: "逾期风险", amount: "¥0.8M" },
  ],

  internalTrade: {
    bridge: [
      { from: "钛虎机器人 PO", mid: "内部结算桥", to: "钛虎精密 SO" },
    ],
    summary: [
      { label: "本月内部额", value: "¥2.4M" },
      { label: "桥接单据", value: "18" },
      { label: "剔除后影响", value: "-12.6%" },
    ],
    samples: [
      { po: "PO-A-25080601", so: "SO-B-25080601", amount: "¥186,000", status: "已桥接", material: "关节模组半成品" },
      { po: "PO-A-25080518", so: "SO-B-25080518", amount: "¥72,400", status: "在途", material: "精密轴件" },
      { po: "PO-A-25080422", so: "SO-B-25080422", amount: "¥128,000", status: "已桥接", material: "减速器组件" },
      { po: "PO-A-25080311", so: "SO-C-25080311", amount: "¥45,600", status: "已完成", material: "线束总成" },
      { po: "PO-A-25080207", so: "SO-B-25080207", amount: "¥96,200", status: "已桥接", material: "结构焊接件" },
    ],
  },

  closedLoop: [
    { name: "线索", sys: "纷享销客", count: 86, conv: null },
    { name: "机会", sys: "纷享销客", count: 42, conv: "48.8%" },
    { name: "订单", sys: "纷享销客", count: 28, conv: "66.7%" },
    { name: "合同", sys: "纷享销客", count: 22, conv: "78.6%" },
    { name: "生产订单", sys: "金蝶", count: 19, conv: "86.4%" },
    { name: "生产入库", sys: "金蝶", count: 15, conv: "78.9%" },
    { name: "发货通知", sys: "金蝶", count: 14, conv: "93.3%" },
    { name: "销售出库", sys: "金蝶", count: 12, conv: "85.7%" },
    { name: "应收", sys: "金蝶", count: 11, conv: "91.7%" },
  ],

  loopKpis: [
    { label: "线索→合同", value: "25.6%", sub: "环比 +2.1pp", tone: "good" },
    { label: "合同→出库周期", value: "18.4", unit: "天", sub: "目标 ≤15 天", tone: "warn" },
    { label: "回款及时率", value: "87.0%", sub: "同比 +4.2pp", tone: "good" },
    { label: "跨系统断点", value: "3", unit: "单", sub: "待人工对齐", tone: "warn" },
    { label: "在途商机金额", value: "¥12.8M", sub: "加权赢率 46%", tone: "neutral" },
  ],

  loopConversions: [
    { stage: "线索 → 机会", rate: "48.8%", drop: 44, cycle: "9.2 天", owner: "销售" },
    { stage: "机会 → 订单", rate: "66.7%", drop: 14, cycle: "12.6 天", owner: "销售" },
    { stage: "订单 → 合同", rate: "78.6%", drop: 6, cycle: "4.1 天", owner: "商务" },
    { stage: "合同 → 生产", rate: "86.4%", drop: 3, cycle: "2.8 天", owner: "PMC" },
    { stage: "生产 → 入库", rate: "78.9%", drop: 4, cycle: "11.0 天", owner: "制造" },
    { stage: "发货 → 出库", rate: "85.7%", drop: 2, cycle: "1.6 天", owner: "仓储" },
    { stage: "出库 → 应收", rate: "91.7%", drop: 1, cycle: "0.8 天", owner: "财务" },
  ],

  loopBottlenecks: [
    { id: "LB-01", stage: "合同→生产订单", issue: "BOM / 工艺待确认", count: 4, owner: "PMC-王敏", age: "3.2天", tone: "warn" },
    { id: "LB-02", stage: "机会→订单", issue: "非标报价超 SLA", count: 5, owner: "销售-陈凯", age: "6.0天", tone: "warn" },
    { id: "LB-03", stage: "出库→应收", issue: "CRM 合同号未回写", count: 3, owner: "IT-对接", age: "1.5天", tone: "danger" },
    { id: "LB-04", stage: "生产→入库", issue: "关键件齐套等待", count: 2, owner: "计划-刘洋", age: "4.8天", tone: "warn" },
    { id: "LB-05", stage: "发货→出库", issue: "物流面单延迟", count: 1, owner: "仓储-赵倩", age: "0.9天", tone: "neutral" },
  ],

  loopSystems: [
    {
      sys: "纷享销客",
      focus: "线索 → 合同",
      health: "正常",
      sync: "5 分钟前",
      metrics: [
        { label: "线索", value: "86", hint: "本月新增 31" },
        { label: "机会", value: "42", hint: "赢率 46%" },
        { label: "合同", value: "22", hint: "金额 ¥9.6M" },
        { label: "跟进逾期", value: "7", hint: "需当日闭环" },
      ],
    },
    {
      sys: "金蝶云星空",
      focus: "生产 → 应收",
      health: "关注",
      sync: "2 分钟前",
      metrics: [
        { label: "生产订单", value: "19", hint: "在制 11" },
        { label: "销售出库", value: "12", hint: "准时 91%" },
        { label: "应收单", value: "11", hint: "未核销 ¥3.1M" },
        { label: "接口失败", value: "3", hint: "待重推" },
      ],
    },
    {
      sys: "飞书 + 北森",
      focus: "项目工时",
      health: "正常",
      sync: "12 分钟前",
      metrics: [
        { label: "在研项目", value: "12", hint: "非标 7" },
        { label: "本周工时", value: "1.8k", hint: "h" },
        { label: "超预算项目", value: "2", hint: "工时预警" },
        { label: "待审批工时", value: "86", hint: "条" },
      ],
    },
  ],

  loopDeals: [
    { name: "华东某整机厂·关节模组", stage: "合同", amount: "¥2.4M", owner: "陈凯", next: "生产下发", eta: "08-07", risk: "正常" },
    { name: "华南集成商·非标臂", stage: "机会", amount: "¥1.8M", owner: "周宁", next: "技术方案评审", eta: "08-09", risk: "交期紧" },
    { name: "华北汽车线·伺服包", stage: "订单", amount: "¥3.1M", owner: "陈凯", next: "合同盖章", eta: "08-08", risk: "正常" },
    { name: "西南物流·视觉单元", stage: "线索", amount: "¥0.9M", owner: "林悦", next: "需求澄清", eta: "08-12", risk: "正常" },
    { name: "出口项目·减速器", stage: "合同", amount: "¥1.5M", owner: "王敏", next: "齐套检查", eta: "08-06", risk: "断点" },
    { name: "教育样机·标品套装", stage: "机会", amount: "¥0.6M", owner: "林悦", next: "报价锁定", eta: "08-11", risk: "正常" },
  ],

  loopReceivables: [
    { no: "AR-2507-018", customer: "华东某整机厂", amount: "¥860,000", due: "08-05", aging: "1天", status: "逾期", owner: "财务-沈洁" },
    { no: "AR-2507-022", customer: "华北汽车线", amount: "¥420,000", due: "08-10", aging: "—", status: "未到期", owner: "财务-沈洁" },
    { no: "AR-2507-009", customer: "出口项目代理", amount: "¥1,150,000", due: "07-28", aging: "9天", status: "催收中", owner: "销售-陈凯" },
    { no: "AR-2508-003", customer: "华南集成商", amount: "¥280,000", due: "08-15", aging: "—", status: "未到期", owner: "财务-沈洁" },
    { no: "AR-2507-031", customer: "西南物流", amount: "¥190,000", due: "08-02", aging: "4天", status: "逾期", owner: "销售-周宁" },
    { no: "AR-2506-044", customer: "教育样机客户", amount: "¥96,000", due: "07-20", aging: "17天", status: "法务跟进", owner: "商务-吴倩" },
  ],
};
