/**
 * 江原研发项目管理 · 仿简道云应用
 * - 字典/字段名取自客户材料
 * - 默认空业务数据：靠表单新增与流程回写产生记录
 * - SAMPLE_* 仅「装载对照样例」时灌入，不作为主路径
 */
window.APP_DATA = {
  meta: {
    appName: "江原研发项目管理",
    appId: "jy-rd-pm",
  },

  projectTypes: ["NPI产品研发项目", "自研项目", "技术服务项目", "产学研项目", "其他"],
  projectStatuses: ["立项准备中", "立项审批中", "执行中", "阶段评审中", "验收审批中", "已结项", "已中止"],
  stages: ["需求调研", "执行规划", "设计实现", "产品验证", "小批量试产", "大批量试产"],
  domains: ["HWG", "SWG", "PEG", "POG", "PCG"],
  taskStatuses: ["未开始", "进行中", "已验收", "已完成", "已取消"],
  taskTypes: ["里程碑任务", "子任务"],
  priorities: ["最高", "较高", "普通", "低"],
  checkStatuses: ["Completed", "Not Completed", "In progress·Not sure", "Completed with waive", "N/A"],
  feeSubjects: ["工艺服务费", "技术服务费", "NRE费用", "基板费用", "辅助材料", "工程加工费", "IP采购费", "固定资产费", "其他"],
  planTemplates: ["NPI默认六阶段", "自研简版", "技术服务简版"],

  members: [
    { id: "m-pm", name: "成员代号-PM" },
    { id: "m-pl", name: "成员代号-PL" },
    { id: "m-hw", name: "成员代号-HW" },
    { id: "m-sw", name: "成员代号-SW" },
    { id: "m-s1", name: "成员代号-S01" },
    { id: "m-s2", name: "成员代号-S02" },
    { id: "m-fin", name: "成员代号-FIN" },
  ],

  /** 业务表单数据（默认空） */
  projects: [],
  tasks: [],
  plans: [],
  todos: [],
  signoffItems: [],
  risks: [],
  contracts: [],
  budgets: {},
  orgMembers: [],
  announcements: [],
  daci: [],
  timeEntries: [],
  feeEntries: [],

  /** 可选对照样例（非默认） */
  _sample: {
    projects: [
      {
        id: "p1",
        code: "JY-RD-2026-0001",
        name: "项目代号-01",
        type: "NPI产品研发项目",
        status: "执行中",
        stage: "设计实现",
        owner: "成员代号-PL",
        coleader: "成员代号-HW",
        pm: "成员代号-PM",
        planStart: "2026-06-01",
        planEnd: "2026-12-20",
        nextNode: "BTO SO Exit Review",
        nextDate: "2026-09-15",
        health: "正常",
        remark: "对照样例",
        flowStatus: "已完成",
        sample: true,
      },
      {
        id: "p2",
        code: "JY-RD-2026-0002",
        name: "项目代号-02",
        type: "自研项目",
        status: "立项审批中",
        stage: "需求调研",
        owner: "成员代号-PL",
        coleader: "成员代号-SW",
        pm: "成员代号-PM",
        planStart: "2026-08-01",
        planEnd: "2026-11-30",
        nextNode: "立项审批",
        nextDate: "2026-08-20",
        health: "正常",
        remark: "对照样例",
        flowStatus: "进行中",
        sample: true,
      },
    ],
    tasks: [
      {
        id: "t1",
        projectId: "p1",
        wbs: "1",
        parentId: null,
        type: "里程碑任务",
        name: "里程碑-BTO-SO",
        path: "HWG",
        stage: "设计实现",
        status: "进行中",
        progress: 62,
        owner: "成员代号-HW",
        participants: "成员代号-S02",
        planStart: "2026-08-01",
        planEnd: "2026-09-15",
        delayed: "正常推进",
        critical: true,
        exitType: "BTO SO Exit Review",
        priority: "最高",
        sample: true,
      },
      {
        id: "t2",
        projectId: "p1",
        wbs: "1.1",
        parentId: "t1",
        type: "子任务",
        name: "任务代号-RTL-Review",
        path: "SWG",
        stage: "设计实现",
        status: "进行中",
        progress: 45,
        owner: "成员代号-S01",
        participants: "成员代号-SW",
        planStart: "2026-08-05",
        planEnd: "2026-08-28",
        delayed: "正常推进",
        critical: false,
        exitType: "",
        priority: "普通",
        sample: true,
      },
      {
        id: "t3",
        projectId: "p1",
        wbs: "1.2",
        parentId: "t1",
        type: "子任务",
        name: "任务代号-Signoff-开签准备",
        path: "POG",
        stage: "设计实现",
        status: "进行中",
        progress: 70,
        owner: "成员代号-PM",
        participants: "成员代号-PL",
        planStart: "2026-07-20",
        planEnd: "2026-08-05",
        delayed: "已延期",
        critical: true,
        exitType: "MRA",
        priority: "最高",
        sample: true,
      },
    ],
    plans: [
      {
        id: "pl1",
        projectId: "p1",
        name: "计划代号-01",
        status: "已确认",
        template: "NPI默认六阶段",
        totalDays: 202,
        sample: true,
      },
    ],
    signoffItems: [
      {
        id: "s1",
        projectId: "p1",
        domain: "SOC Design",
        tag1: "Design",
        tag2: "RTL",
        tag3: "REG",
        description: "检查项代号-C01：Register RALF reviewed",
        check: "Not Completed",
        owner: "成员代号-S01",
        approver: "成员代号-HW",
        approval: "Pending",
        comments: "",
        sample: true,
      },
      {
        id: "s2",
        projectId: "p1",
        domain: "IP",
        tag1: "IP",
        tag2: "Integration",
        tag3: "DOC",
        description: "检查项代号-C02",
        check: "Completed",
        owner: "成员代号-S02",
        approver: "成员代号-SW",
        approval: "Approved",
        comments: "Approved by 成员代号-SW",
        sample: true,
      },
    ],
    risks: [
      {
        id: "r1",
        projectId: "p1",
        type: "风险",
        dimension: "进度",
        desc: "风险代号-RK01：关键里程碑临近",
        level: "高",
        status: "进行中",
        owner: "成员代号-PM",
        eta: "2026-08-20",
        sample: true,
      },
    ],
    budgets: {
      p1: {
        manMonthPlan: 120,
        manMonthActual: 78,
        feePlan: 860,
        feeActual: 612,
        subjects: [
          { name: "工艺服务费", plan: 120, actual: 98 },
          { name: "NRE费用", plan: 200, actual: 180 },
          { name: "IP采购费", plan: 150, actual: 90 },
          { name: "其他", plan: 30, actual: 7 },
        ],
      },
    },
  },
};
