/**
 * 经营看板 · 数据层
 * 指标口径对齐决策看板 v1（SAP/MES/ATE 演示基线），面向 CEO 晨间例会。
 */
window.OPS_DASHBOARD = {
  meta: {
    product: "经营简报",
    edition: "晨间例会",
    asOf: "2026-07-13 08:00",
    asOfLabel: "数据截至 7/13 晨 · SAP T-1",
    company: "壁仞科技",
  },

  /** CEO 打开第一屏只看这三句 */
  brief: {
    headline: "逾期上升拖累现金质量，物料缺口制约交付；今日需完成两项决策。",
    points: [
      {
        tone: "bad",
        title: "逾期 1,240 万，较上周 +180 万",
        detail: "本月回款 2,860 万已达目标，但账龄结构恶化；回款额无法对冲新增逾期。",
        metricId: "bi.finance.overdue_total",
      },
      {
        tone: "bad",
        title: "板卡备料 86%，UBB 缺料影响 2 个批次",
        detail: "合同与出货承诺仍在；关键桥接卡未齐套，验收与收入确认将顺延。",
        metricId: "bi.supply.board_prep",
      },
      {
        tone: "warn",
        title: "采购合同待签 12 份，其中封测框架 4 份",
        detail: "未签署则无法锁定 Q3 封测产能，芯片出货承诺将承压。",
        metricId: "bi.supply.purchase_contract",
      },
    ],
  },

  /** 脉搏数字：直接复用 v1 口径，给 CEO 锚点 */
  pulse: [
    {
      id: "bi.finance.collection_month",
      name: "本月回款",
      value: "2,860",
      unit: "万",
      delta: "+12%",
      vs: "上月同期",
      tone: "good",
      source: "SAP 回款追踪",
      why: "本月目标完成率 108%；回款额达标，但账龄质量需分开看。",
    },
    {
      id: "bi.finance.overdue_total",
      name: "逾期总额",
      value: "1,240",
      unit: "万",
      delta: "+180万",
      vs: "上周",
      tone: "bad",
      source: "SAP 回款追踪",
      why: "超期未回持续增加，需销售高管层介入催收。",
    },
    {
      id: "bi.supply.board_prep",
      name: "板卡备料",
      value: "86",
      unit: "%",
      delta: "-4pp",
      vs: "计划",
      tone: "bad",
      source: "供应链计划",
      why: "UBB 桥接卡缺料，已影响 2 个交付批次。",
    },
    {
      id: "bi.inventory.m_turn",
      name: "M料周转",
      value: "23.6",
      unit: "天",
      delta: "+2.6天",
      vs: "安全线 21",
      tone: "warn",
      source: "库存管理",
      why: "长库龄占比上升，占用营运资金。",
    },
    {
      id: "bi.production.chip_shipment",
      name: "累计出货",
      value: "12.8",
      unit: "万片",
      delta: "+1.2万",
      vs: "上周",
      tone: "good",
      source: "SAP 交货 / MES",
      why: "Q3 出货承诺完成率 94%。",
    },
    {
      id: "bi.production.test_yield",
      name: "测试良率",
      value: "94.8",
      unit: "%",
      delta: "-0.3pp",
      vs: "昨日",
      tone: "good",
      source: "ATE 测试系统",
      why: "BR104 主力批次稳定；单批 Bin2 偏高，待质量复盘。",
    },
    {
      id: "bi.org.attendance_today",
      name: "今日到岗",
      value: "96.2",
      unit: "%",
      delta: "封测 89%",
      vs: "全公司",
      tone: "warn",
      source: "组织考勤",
      why: "封测工程部到岗偏低，可能影响入库与出货。",
    },
    {
      id: "bi.supply.purchase_contract",
      name: "待签合同",
      value: "12",
      unit: "份",
      delta: "4 份封测",
      vs: "框架协议",
      tone: "warn",
      source: "采购合同台账",
      why: "封测框架未签，Q3 排产尚未锁定。",
    },
  ],

  /**
   * 五个转换摩擦 —— 每条必须挂真实指标，而不是抽象口号
   */
  frictions: [
    {
      id: "revenue-cash",
      from: "收入",
      to: "现金",
      status: "red",
      title: "逾期上升，现金质量承压",
      metric: { name: "逾期总额", value: "1,240", unit: "万", delta: "周+180万" },
      impact: "本周若不压降，账龄将继续侵蚀回款成果",
      owner: "销售VP × CFO",
      due: "本周五",
      evidence: "SAP：超期未回 1,240 万；本月回款 2,860 万已达成，但无法对冲新增逾期。",
      next: "Top5 逾期客户名单 + 催收回笼节点签字",
      askCeo: false,
    },
    {
      id: "inventory-delivery",
      from: "库存",
      to: "交付",
      status: "red",
      title: "UBB 缺料制约批次交付",
      metric: { name: "板卡备料", value: "86", unit: "%", delta: "差计划 4pp" },
      impact: "2 个交付批次验收后移，收入确认相应延期",
      owner: "COO / 供应链",
      due: "今日 13:30 短会",
      evidence: "关键型号板卡备料 86%；UBB 桥接卡缺料；M 料周转 23.6 天，高于安全线 21 天。",
      next: "确认替代 BOM 方案 B 是否可执行",
      askCeo: true,
    },
    {
      id: "contract-revenue",
      from: "合同",
      to: "收入",
      status: "amber",
      title: "封测框架未签，Q3 产能未锁定",
      metric: { name: "待签合同", value: "12", unit: "份", delta: "含 4 份封测" },
      impact: "Q3 芯片排产与出货承诺承压",
      owner: "采购 × 供应链",
      due: "本周内",
      evidence: "12 份采购合同待签署，其中 4 份为封测产能框架协议。",
      next: "4 份框架本周强制过会签署",
      askCeo: true,
    },
    {
      id: "rd-product",
      from: "研发",
      to: "产品",
      status: "green",
      title: "出货与良率维持可控",
      metric: { name: "测试良率", value: "94.8", unit: "%", delta: "出货 12.8 万片" },
      impact: "产品侧暂非今日优先项，按月度里程碑推进",
      owner: "CTO",
      due: "月度里程碑会",
      evidence: "YTD 出货 12.8 万片，完成率 94%；FT 良率 94.8%。",
      next: "异常 Bin2 批次复盘结论备案",
      askCeo: false,
    },
    {
      id: "talent-result",
      from: "人才",
      to: "结果",
      status: "amber",
      title: "封测到岗偏低，入库存在风险",
      metric: { name: "今日到岗", value: "96.2", unit: "%", delta: "封测 89%" },
      impact: "若连续两日，入库与出货节点将受影响",
      owner: "组织 / 封测负责人",
      due: "今日确认",
      evidence: "全公司到岗 96.2%，封测工程部 89%，为全公司最低。",
      next: "确认是否已影响良率/入库，必要时调班",
      askCeo: false,
    },
  ],

  /** 只有真正要 CEO 拍板的才进这里 */
  decisions: [
    {
      id: "d1",
      urgency: "今日",
      title: "批准 UBB 替代 BOM 方案 B？",
      stake: "不批准：2 个批次继续受阻。批准：替代料认证与质量风险需 CTO、质量联签。",
      metricHook: "板卡备料 86% · 缺口影响 2 批次",
      options: [
        { id: "a", label: "批准执行方案 B", cost: "替代料认证周期约 5–7 天", recommend: true },
        { id: "b", label: "继续等待原厂料", cost: "交期继续后移，客户承诺存在失信风险", recommend: false },
        { id: "c", label: "拆单交付部分批次", cost: "交付体验下降，收入确认更为分散", recommend: false },
      ],
      dri: "CEO",
      support: "供应链负责人 · 今日 13:30 带方案进会",
    },
    {
      id: "d2",
      urgency: "本周",
      title: "逾期催收是否升级至销售高管层？",
      stake: "逾期 1,240 万，周增 180 万；回款达标无法掩盖账龄恶化。",
      metricHook: "逾期 1,240 万 · 周+180 万",
      options: [
        { id: "a", label: "升级：Top5 客户由销售VP周盯", cost: "占用销售高管管理带宽", recommend: true },
        { id: "b", label: "维持现行催收机制", cost: "逾期可能继续上升", recommend: false },
        { id: "c", label: "先由 CFO 完成账龄分层再定", cost: "额外耗时 2–3 天", recommend: false },
      ],
      dri: "CEO",
      support: "销售VP × CFO",
    },
    {
      id: "d3",
      urgency: "本周",
      title: "4 份封测框架是否本周完成签署？",
      stake: "未签则 Q3 产能无法锁定，芯片出货承诺将先承压。",
      metricHook: "待签 12 份 · 其中 4 份封测框架",
      options: [
        { id: "a", label: "本周过会完成签署", cost: "商务条款需快速收敛", recommend: true },
        { id: "b", label: "先签 2 份高优先级", cost: "产能仅锁定约一半", recommend: false },
        { id: "c", label: "延后至下周", cost: "排产空档继续扩大", recommend: false },
      ],
      dri: "CEO",
      support: "采购 × 供应链",
    },
  ],

  /** 承诺 = 有 DRI、截止日、验收标准；对齐 v1 待办 */
  commitments: [
    {
      id: "c1",
      title: "确认 UBB 替代方案并解除 2 批次阻塞",
      result: "备料完成率回升至 90%+，或给出不可解除的书面原因",
      stage: "待验收",
      status: "red",
      dri: "供应链负责人",
      acceptor: "COO",
      due: "今天 18:00",
      evidence: "13:30 短会已排；方案 B 待 CEO 决策",
      escalate: "今日未完成 → 明早站会提报 CEO",
      linkedMetric: "bi.supply.board_prep",
    },
    {
      id: "c2",
      title: "Top5 逾期催收回笼计划签字启动",
      result: "可追踪的回笼金额与日期；本周目标压降 200 万",
      stage: "执行中",
      status: "red",
      dri: "销售VP",
      acceptor: "CFO",
      due: "周五",
      evidence: "逾期总额 1,240 万，周增 180 万",
      escalate: "单户超期未回笼 → 升级 CEO",
      linkedMetric: "bi.finance.overdue_total",
    },
    {
      id: "c3",
      title: "4 份封测产能框架协议签署",
      result: "合同生效，Q3 相关产能可排产",
      stage: "已定责",
      status: "amber",
      dri: "采购负责人",
      acceptor: "供应链负责人",
      due: "本周五",
      evidence: "12 份待签中 4 份为封测框架",
      escalate: "周五未签满 4 份 → 升级 CEO",
      linkedMetric: "bi.supply.purchase_contract",
    },
    {
      id: "c4",
      title: "收入预测商机折算口径对齐（÷1.13）",
      result: "销售VP 与 CFO 共用同一套全年预测口径",
      stage: "执行中",
      status: "amber",
      dri: "销售VP",
      acceptor: "CFO",
      due: "7/14",
      evidence: "口径不一致会导致董事会与经营会数字对不上",
      escalate: "7/14 未对齐 → 经营例会升级",
      linkedMetric: null,
    },
    {
      id: "c5",
      title: "封测到岗是否影响入库的确认回复",
      result: "书面确认：无影响 / 有影响及补救班次",
      stage: "已立项",
      status: "amber",
      dri: "封测负责人",
      acceptor: "COO",
      due: "今日 12:00",
      evidence: "封测到岗 89%，全公司 96.2%",
      escalate: "午间未回复 → 站会点名",
      linkedMetric: "bi.org.attendance_today",
    },
  ],

  battles: [
    {
      id: "b1",
      name: "订单交付",
      goal: "合同签署 → 备料 → 出货 → 验收 → 收入确认，按节点完成",
      status: "red",
      progress: 28,
      owner: "COO × 销售",
      now: "UBB 缺料 + 封测框架未签，是当前最大阻塞",
      kpis: ["备料 86%→90%+", "阻塞批次清零", "验收按期"],
    },
    {
      id: "b2",
      name: "现金与库存",
      goal: "逾期压降、周转回到安全线",
      status: "red",
      progress: 35,
      owner: "CFO × 销售VP",
      now: "逾期 1,240 万，周增 180 万；M 料周转 23.6 天",
      kpis: ["逾期压降 200 万/周", "周转≤21 天", "回款质量"],
    },
    {
      id: "b3",
      name: "BR20X 量产落地",
      goal: "样板客户验收路径清晰，里程碑证据齐备，软件适配按表推进",
      status: "amber",
      progress: 42,
      owner: "CTO × 商业化",
      now: "出货与良率基本盘仍在；量产与样板验收需单独盯表",
      kpis: ["里程碑证据", "样板验收路径", "软件适配"],
    },
    {
      id: "b4",
      name: "跨域定责",
      goal: "跨域事项按责任人推进，减少默认升级创始人",
      status: "amber",
      progress: 20,
      owner: "CEO",
      now: "今日仍有 2 项待 CEO 决策——跨域定责机制尚未托住日常事项",
      kpis: ["提报 CEO 事项下降", "责任人清晰", "周会决策/协调比"],
    },
  ],

  externalFocus: [
    {
      tag: "政策",
      text: "智算采购能效门槛或抬升",
      why: "影响客户选型与 TCO；产品与售前核对现有方案能效表述。",
    },
    {
      tag: "客户",
      text: "推理算力需求结构变化",
      why: "可能改整机配置与出货排期；销售盯 Q3 在手承诺。",
    },
    {
      tag: "竞品",
      text: "国产 DPU 与区域智采推进加快",
      why: "客户比的是整机方案完整性与区域供货能力。",
    },
  ],
};
